### ISSUE TITLE
RuntimeError - QgsVectorLayer has been deleted

### ISSUE THREAD

**Issue by robbitt** [opengisch/QField#3887]
### Describe the issue
In QGIS, I attempted to set the Layer Properties for a QField layer - Cable layer action to offline editing.  This launches a popup window that says:

An error has occurred while executing Python code: 

```
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted 
Traceback (most recent call last):
  File "C:\Users/Owner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\layers_config_widget.py", line 93, in 
    lambda msg: self._on_message_bus_messaged(msg)
  File "C:\Users/Owner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\layers_config_widget.py", line 274, in _on_message_bus_messaged
    layer_source.read_layer()
  File "C:\Users/Owner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\libqfieldsync\layer.py", line 101, in read_layer
    self._action = self.layer.customProperty("QFieldSync/action")
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.3-Firenze Firenze, c12bcb2f76c 
```

### Reproduction steps
1. Launch QGIS
2. Layer Properties
3. Scroll down to 'QField'
4. Set 'Cable layer action' to 'Offline editing'

### Expected behavior
[A clear and concise description of what you expected to happen.]

### Observed behavior
Multiple Error windows popup

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.28.3
 - QFieldSync Version 4.2.0

### Mobile (please complete the following information)
 - OS: [e.g. Android 11]
 - QField version: [Enter QField version here including build number found in the about screen after the release name example 2.0.0 (10200993)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: No
* Problem happens with all files and projects, not only some files or projects: No, differs by project

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by suricactus** [comment]
Can you please attach a minimal sample project that reproduces the issue.

**Comment by antoniusz** [comment]
It may be related to:
https://github.com/opengisch/qfieldsync/issues/468

**Comment by Amphibitus** [comment]
I had the same problem. 
After replacing ".jpg" with "{extension}" in the photo name property , the error no longer occurred ?!
