### ISSUE TITLE
Python error using using latest release of QField Sync v4.3.0

### ISSUE THREAD

**Issue by bakkerss** [opengisch/QField#3896]
I have updated the plugin to the latest version. However, when I press the button "Synchronize from QFIELD" I immediately receive a Python error: "An error occurred while executing Python code:"

I can only solve the issue by installing the previous version of the plugin as the new release is unusable. What is causing this issue?

Herre  details of the error:

```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
Traceback (most recent call last):
  File "C:\Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\qfield_sync.py", line 351, in show_synchronize_dialog
    dlg = SynchronizeDialog(
  File "C:\Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\synchronize_dialog.py", line 68, in __init__
    import_dir = self.preferences.value("importDirectoryProject")
  File "C:\Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\setting_manager\setting_manager.py", line 54, in value
    return self.__settings[setting_name].value()
  File "C:\Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\setting_manager\setting.py", line 192, in value
    value = self.read_out(value, self.scope)
  File "C:\Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\setting_manager\types\dictionnary.py", line 57, in read_out
    return json.loads(value)
  File "C:\OSGeo4W\apps\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\OSGeo4W\apps\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\OSGeo4W\apps\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.2-Firenze Firenze, b47e00ba601 

Python pad:
C:/OSGeo4W/apps/qgis/./python
C:/Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:/Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\SebastiaanBakker\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\SebastiaanBakker\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\SebastiaanBakker\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
C:/Users/SebastiaanBakker/Natuurlink B.V/Natuurlink - Documenten/QGIS/Woonstichting Laurentius
```

### Desktop (please complete the following information)
- OS: [Windows 11]
Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.2-Firenze Firenze, b47e00ba601

**Comment by suricactus** [comment]
@bakkerss hey, thanks for the quick report, very welcome. Please upgrade to QFieldSync 4.3.1 and error should be gone.

**Comment by bakkerss** [comment]
@suricactus I tested this and the error is gone. Thanks for the quick fix! Much appreciated!.
