### ISSUE TITLE
Problem with path creating package

### ISSUE THREAD

**Issue by Lanjal** [opengisch/QField#4090]
### Describe the issue
After updating to the newst version 4.4.9 an error in gdal apeared, it not GDAL but the shutil.py slash back-slash formating perhaps

2023-03-29T07:05:45     WARNING    Traceback (most recent call last):
              File "C:\Users/andre.costa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\package_dialog.py", line 175, in package_project
              raise err
              File "C:\Users/andre.costa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\package_dialog.py", line 171, in package_project
              offline_convertor.convert()
              File "C:\Users/andre.costa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\libqfieldsync\offline_converter.py", line 141, in convert
              self._convert(project)
              File "C:\Users/andre.costa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\libqfieldsync\offline_converter.py", line 277, in _convert
              copied_files = layer_source.copy(self.export_folder, copied_files)
              File "C:\Users/andre.costa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\libqfieldsync\layer.py", line 522, in copy
              shutil.copy(os.path.join(source_path, basename + ext), dest_file)
              File "C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\shutil.py", line 418, in copy
              copyfile(src, dst, follow_symlinks=follow_symlinks)
              File "C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\shutil.py", line 244, in copyfile
              raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
             shutil.SameFileError: '**C:/Users/andre.costa/Desktop/MRN2/PRODUTO FINAL/checklistqfield\\MRN_BASE.shp'** and **'C:\\Users\\andre.costa\\Desktop\\MRN2\\PRODUTO FINAL\\checklistqfield\\MRN_BASE.shp'** are the same file

The path seems to be misconfigured (Windows format and linux format)

**Comment by nirvn** [comment]
@Lanjal , is this still a problem with the latest QFieldSync version?
